project:
  type: website
  output-dir: docs
  resources:
    - CNAME  # This means "hey Quarto, don't delete this file!"

website:
  title: "karlve.com"
  navbar:
    right:
      - about.qmd
      - text: "CV"
        href: "https://docs.google.com/document/d/1p3t-C2WdBLR2Mzka6oRuCfuDtN2X6dtAeCcjir_1ml0/export?format=pdf"
      - icon: github
        href: https://github.com/karlcal1
      - icon: linkedin
        href: https://www.linkedin.com/in/karl-vilhelmsson-emneby-a40267215/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



